app:
  image: ibmcom/swift-ubuntu:4.0.3
  volumes:
    - .:/AlertNotifications
  command: bash -c "cd /AlertNotifications && swift package --build-path .build-ubuntu clean && swift build --build-path .build-ubuntu && swift test --build-path .build-ubuntu"
